fmit/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static

from rest_framework import routers

from news import views

router = routers.DefaultRouter()
router.register(r'news', views.NewsViewSet)
router.register(r'volume', views.VolumeViewSet)


urlpatterns = [
    url(r'^$', views.home),
    url(r'^', include('django.contrib.auth.urls')),
    url(r'^news/', include('news.urls', namespace='news')),
    url(r'^working-mac/(?P<slug>.*)/$', views.MacSkillDetail.as_view(), name='working-mac'),
    url(r'^audience/', include('audience.urls', namespace='audience')),
    url(r'^zu/', include('lease.urls', namespace='lease')),

    url(r'^comments/', include('django_comments.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

news/urls.py
from django.conf.urls import include, url
from news import views
from news.views import VolumeAutocomplete

urlpatterns = [
    url(r'^p/(?P<page>\d*)/$', views.news_list, name='news_list_page'),
    url(r'^(?P<id>\d*)\.html$', views.news_detail, name='news_detail'),
    url(r'^volume-autocomplete/$', VolumeAutocomplete.as_view(), name='volume-autocomplete'),
]

news/models.py
# coding=UTF-8
import hashlib
from urllib import urlretrieve

from django.conf import settings
from django.core.files import File
from django.db import models
from django.utils import timezone
from tagging.registry import register

from tinymce.models import HTMLField
import re


# Create your models here.

def strip_html(html):
    return re.sub(r'<.*?>', '', html)


class Source(models.Model):
    key = models.CharField(u"来源站ID", max_length=50, primary_key=True)
    name = models.CharField(u"网站名称", max_length=50)
    url = models.URLField(u"网址")
    active = models.BooleanField(u"抓取", default=True)
    running = models.BooleanField(u"抓取中", default=False)
    interval = models.DurationField(u"抓取间隔")
    url_list = models.URLField(u"列表地址")
    created = models.DateTimeField(u"创建时间", auto_now_add=True)
    updated = models.DateTimeField(u"更新时间", auto_now=True)
    re_list = models.TextField(u"列表正则")
    renum_newsid = models.SmallIntegerField(u"正则结果：来源站文章ID", default=0)
    renum_url = models.SmallIntegerField(u"正则结果：URL", default=1)
    reopt_url_isrelative = models.BooleanField(u"正则选项：URL", default=True, help_text=u"选中后，正则匹配的URL前会加上站点网址")
    renum_title = models.SmallIntegerField(u"正则结果：标题", default=2)
    renum_thumb = models.SmallIntegerField(u"正则结果：缩略图", default=5)
    renum_introduce = models.SmallIntegerField(u"正则结果：简介", default=6)
    renum_pubdate = models.SmallIntegerField(u"正则结果：文章时间", default=4)
    renum_publisher = models.SmallIntegerField(u"正则结果：撰稿人", default=3)
    re_content = models.TextField(u"内容正则")

    def __unicode__(self):
        return self.name

    def sync(self):
        import httplib2
        if not self.active and self.running:
            return 0
        self.running = True
        self.save()
        h = httplib2.Http()
        resp, content = h.request(self.url_list)
        # print resp, content
        if resp['status'] == '200':
            pass
        items = re.findall(str(self.re_list), content, re.DOTALL)
        total = 0
        for item in items:
            try:
                News.objects.get(source=self, newsid=item[self.renum_newsid])
                continue
            except News.DoesNotExist:
                pass
            news = News()
            news.source = self
            news.newsid = item[self.renum_newsid]
            if self.reopt_url_isrelative:
                news.url = self.url + item[self.renum_url]
            else:
                news.url = item[self.renum_url]
            news.title = strip_html(item[self.renum_title])
            news.thumb_url = item[self.renum_thumb]
            news.introduce = strip_html(item[self.renum_introduce])
            news.pubdate = item[self.renum_pubdate]
            news.publisher = item[self.renum_publisher]
            # store thumb
            if news.thumb_url:
                try:
                    result = urlretrieve(news.thumb_url)
                    file_ext = result[0].split('.')[1]
                    file = open(result[0], 'rb')
                    news.thumb.save('%s.%s' % (hashlib.md5(file.read()).hexdigest(), file_ext),
                                    File(file))
                except IOError:
                    pass
            news.save()

            # fetch content
            resp, content = h.request(news.url)
            match = re.search(self.re_content, content, re.DOTALL)
            if match:
                content = Content()
                content.news = news
                content.content = match.groups()[0]
                content.save()

            total += 1
        self.running = False
        self.updated = timezone.localtime(timezone.now())
        self.save()
        return total

    class Meta:
        verbose_name = u"数据来源"
        verbose_name_plural = verbose_name


class News(models.Model):
    source = models.ForeignKey(Source, verbose_name=u"来源站")
    newsid = models.IntegerField(u"来源站文章ID")
    url = models.URLField(u"原文URL")
    title = models.CharField(u"标题", max_length=250, db_index=True)
    thumb = models.ImageField(u"封面图", upload_to="news_thumb")
    thumb_url = models.URLField(u"封面图URL")
    introduce = models.CharField(u"简介", max_length=250)
    pubdate = models.DateTimeField(u"新闻时间", db_index=True)
    publisher = models.CharField(u"撰稿人", max_length=100)
    created = models.DateTimeField(u"创建时间", auto_now_add=True)
    updated = models.DateTimeField(u"更新时间", auto_now=True)
    support = models.IntegerField(u"支持数", default=0)
    oppose = models.IntegerField(u"反对数", default=0)

    def __unicode__(self):
        return self.title

    class Meta:
        verbose_name = u"新闻"
        verbose_name_plural = verbose_name
        ordering = ['-pubdate']
        unique_together = (("source", "newsid"),)


class Content(models.Model):
    news = models.OneToOneField(News, verbose_name=u"新闻")
    content = HTMLField(u"文章内容")

    def __unicode__(self):
        return self.news.title

    class Meta:
        verbose_name = u"新闻内容"
        verbose_name_plural = verbose_name


class Volume(models.Model):
    VOLUME_STATUS_COLLECT = 0
    VOLUME_STATUS_RECORD = 1
    VOLUME_STATUS_RELEASE = 2
    VOLUME_STATUS = (
        (VOLUME_STATUS_COLLECT, u"话题征集中"),
        (VOLUME_STATUS_RECORD, u"正在录音"),
        (VOLUME_STATUS_RELEASE, u"已发布"),
    )
    VOLUME_CATEGORY_GENERAL = 0
    VOLUME_CATEGORY_SPEC = 1
    VOLUME_CATEGORY_WEEKLY = 2
    VOLUME_CATEGORY_DISCUSS = 3
    VOLUME_CATEGORY = (
        (VOLUME_CATEGORY_GENERAL, u"VOL"),
        (VOLUME_CATEGORY_SPEC, u"Spec"),
        (VOLUME_CATEGORY_WEEKLY, u"Weekly"),
        (VOLUME_CATEGORY_DISCUSS, u"Discuss"),
    )

    vol = models.IntegerField(u"期")
    subject = models.CharField(u"节目标题", max_length=200)
    status = models.SmallIntegerField(u"状态", choices=VOLUME_STATUS, default=VOLUME_STATUS_COLLECT, db_index=True)
    category = models.SmallIntegerField(u"类型", choices=VOLUME_CATEGORY, default=VOLUME_CATEGORY_GENERAL, db_index=True)
    album = models.ImageField(u"封面", upload_to='album')
    collect = models.CharField(u"征集文", max_length=255)
    digi_rec = None
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return "FMiT.VOL%d %s" % (self.vol, self.subject)

    class Meta:
        verbose_name = u"节目"
        verbose_name_plural = verbose_name
        ordering = ['-vol']


class Information(models.Model):
    volume = models.ForeignKey(Volume)
    subject = models.CharField(u"新闻标题", max_length=200)
    news = models.ForeignKey(News, blank=True, null=True)

    def __unicode__(self):
        return self.volume


class MacSkill(models.Model):
    brow = models.SlugField(u"URL", unique=True)
    volume = models.OneToOneField(Volume, related_name='mac_skill')
    subject = models.CharField(u"技巧标题", max_length=200)
    cmd = models.CharField(u"Command Line", max_length=255, blank=True)
    url = models.URLField(u"来源", blank=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, editable=False)
    is_publish = models.BooleanField(u"发布", default=False, db_index=True)

    def __unicode__(self):
        return self.subject

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('working-mac', args=(self.brow,))

    class Meta:
        verbose_name = u"mac技巧"
        verbose_name_plural = verbose_name


register(MacSkill)


class MacSkillContent(models.Model):
    mac_skill = models.OneToOneField(MacSkill)
    content = HTMLField(u"技巧内容")

news/forms.py
# coding=UTF-8
from dal import autocomplete
from django import forms

from news.models import MacSkill


class MacSkillForm(forms.ModelForm):

    class Meta:
        model = MacSkill
        fields = '__all__'
        widgets = {
            'volume': autocomplete.ModelSelect2(
                url='news:volume-autocomplete',
                attrs={
                    'data-placeholder': u'输入节目期号或者标题...',
                    'data-minimum-input-length': 2,
                })
        }

news/views.py
from django.contrib.contenttypes.models import ContentType
from django.shortcuts import render
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from dal import autocomplete
from django.views.generic import DetailView
from django_comments.models import Comment
from rest_framework import viewsets, status
from rest_framework.decorators import detail_route
from rest_framework.pagination import CursorPagination
from rest_framework.response import Response

from .models import News, Volume, MacSkill
from .serializers import NewsSerializer, VolumeSerializer, CommentSerializer


# Create your views here.


def home(request):
    # coll
    vol_coll = Volume.objects.filter(status=Volume.VOLUME_STATUS_COLLECT)[:10]
    vol_release = Volume.objects.filter(status=Volume.VOLUME_STATUS_RELEASE)[:10]

    return render(request, 'news/home.html', {
        'vol_coll': vol_coll,
        'vol_release': vol_release,
    })


def news_list(request, page=1):
    list = News.objects.all()
    paginator = Paginator(list, 20)
    try:
        list = paginator.page(page)
    except PageNotAnInteger:
        list = paginator.page(1)
    except EmptyPage:
        list = paginator.page(paginator.num_pages)
    return render(request, 'news/list.html', {'list': list})


def news_detail(request, id):
    news = News.objects.get(pk=id)
    return render(request, 'news/detail.html', {'news': news})


class MacSkillDetail(DetailView):
    model = MacSkill
    slug_field = 'brow'


# DAL


class VolumeAutocomplete(autocomplete.Select2QuerySetView):

    def get_queryset(self):
        if not self.request.user.is_authenticated():
            return Volume.objects.none()
        qs = Volume.objects.all()
        if self.q:
            try:
                vol_int = int(self.q)
                qs = qs.filter(vol=vol_int)
            except ValueError:
                qs = qs.filter(subject__contains=self.q)

        return qs


# DRF


class NewsResultsSetPagination(CursorPagination):
    ordering = '-pubdate'


class NewsViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = News.objects.all()
    serializer_class = NewsSerializer
    pagination_class = NewsResultsSetPagination


class VolumeViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = Volume.objects.all()
    serializer_class = VolumeSerializer

    @detail_route(methods=['GET','POST'])
    def comments(self, request, pk=None):
        volume = self.get_object()
        content_type = ContentType.objects.get(app_label="news", model="volume")

        if request.method == 'GET':
            queryset = Comment.objects.filter(content_type=content_type,
                                              object_pk=volume.pk,
                                              is_removed=False,
                                              is_public=True).order_by('-submit_date')
            # page = self.paginate_queryset(queryset)
            # if page is not None:
            # serializer = CommentSerializer(page, many=True)
            # return self.get_paginated_response(serializer.data)
            serializer = CommentSerializer(queryset, many=True)

            return Response({'results': serializer.data})
        elif request.method == 'POST':
            comment, created = Comment.objects.get_or_create(user=request.user, content_type=content_type,
                                                             object_pk=volume.pk, site_id=1,
                                                             comment=request.data['comment'], is_removed=False)
            if created:
                st = status.HTTP_201_CREATED
            else:
                st = status.HTTP_400_BAD_REQUEST
            serializer = CommentSerializer(comment)
            return Response(serializer.data, status=st)

templates/news/detail.html
{% extends "base.html" %}
{% load comments %}

{% block content %}
<h1>{{ news.title }}</h1>

<div class="news-content">
  {{ news.introduce }}
</div>

<div class="news-content-safe">
  {{ news.content.content|safe }}
</div>

{% render_comment_form for news %}
{# {% render_comment_list for news %} #}

{% endblock %}

templates/news/home.html
{% extends 'base.html' %}
{% load static %}
{% load comments %}

{% block content %}
<h1>话题讨论征集中</h1>

<section>
  <ul class="fmit-main">
  {% for vol in vol_coll %}
  {% get_comment_count for vol as comment_count %}
    <li class=" article">
      <a href="#pageComment" class="clearfix"  id="{{ vol.id }}">
        {% if vol.album %}<img src="{{ vol.album.url }}" alt="新闻标题"/>{% endif %}
        <div class="article-detail">
          <h2 class="article-title">{{ vol }}</h2>
          <p class="article-footer">{{ vol.collect }}</p>
          {% if comment_count %}<p class="comment">{{ comment_count }}评论</p>{% endif %}
        </div>
      </a>
    </li>
  {% endfor %}
  </ul>
</section>

<h1>往期节目</h1>
<section class="home">
  <ul class="fmit-main">
  {% for vol in vol_release %}
  {% get_comment_count for vol as comment_count %}
    <li class="article">
      <a href="#pageComment" class="clearfix" id="{{ vol.id }}">
        {% if vol.album %}<img src="{{ vol.album.url }}" alt="新闻标题"/>{% endif %}
        <div class="article-detail">
          <h2 class="article-title">{{ vol }}</h2>
          <p class="article-footer">{{ vol.collect }}</p>
          {% if comment_count %}<p class="comment">{{ comment_count }}评论</p>{% endif %}
        </div>
      </a>
    </li>
  {% endfor %}
  </ul>
</section>

{% endblock %}

templates/news/list.html
{% extends "base.html" %}

{% block content %}
<div class="row">
  <!--<div class="col-md-4"></div>-->
  <div class="col-md-12 nopadding">
    <ul  class="list-group">
    {% for news in list %}
    <li class="list-group-item fmit-list {% cycle 'row0' 'row1' %}">
      <p><a href="{% url 'news:news_detail' id=news.pk %}" class="newsListLink">{{ news.title }}</a></p>
        {% if news.thumb %}<img src="{{ news.thumb.url }}" alt="{{ news.title }}" />{% endif %}
      <span class="newsListLinkContent">{{ news.introduce }}</span>
      <p class="newsListFooter">{{ news.pubdate }}</p>
      <em>支持：{{ news.support }}</em><i>反对：{{ news.oppose }}</i>
    </li>
    {% endfor %}
    </ul>
  </div>
  <!--<div class="col-md-4"></div>-->
</div>

<div class="pagination">
{% if list.has_previous %}
<a href="{% url 'news:news_list_page' page=list.previous_page_number %}">上一页</a>
{% endif %}
{{ list.number }} / {{ list.paginator.num_pages }}
{% if list.has_next %}
<a href="{% url 'news:news_list_page' page=list.next_page_number %}">下一页</a>
{% endif %}
</div>

{% endblock %}

templates/news/macskill_detail.html
{% extends 'base.html' %}
{% load tagging_tags %}
{% load static %}
{% block content %}
    <div class="macskill">
        <header>
            <h2>{{ object.subject }}</h2>
            <h4>{{ object.cmd }}</h4>
            {% if object.url %}<h5>来源{{ object.url }}</h5>{% endif %}
            <p class="author">
                作者：{{ object.author.first_name }}
            </p>
            <div class="tags">
                <p>
                    <em>Tags：</em>
                    {% tags_for_object object as tags %}
                    {% for tag in tags %}
                    <span>{{ tag }}</span>
                    {% endfor %}
                </p>

            </div>
        </header>


        <section class="">
            {{ object.macskillcontent.content|safe }}
        </section>
        <footer>
            <div class="clearfix">
                <p>出处: </p>
                <p>{{ object.volume }}</p>
            </div>
            <div class="links">
                <p>【微信号】：FMiT</p>
                <img src="{% static "news/images/weixin_qrcode.jpg" %}" alt="【微信号】：FMiT">
            </div>
        </footer>
    </div>
{% endblock %}